config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article_id, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end
  def show
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@article)
  end
  def edit
  end
  def update
    @article.update(article_params)
    redirect_to articles_path(@article)
  end
  def destroy
    @article.destroy
    redirect_to articles_path(@article)
  end
  private
  def find_article_id
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.htm.erb
<%= form_for(@article) do |f| %>
	  <%= f.label :name %>
	  <%= f.text_field :name %>
	  <%= f.label :content %>
	  <%= f.text_field :content %>


	  <%= f.submit %>
	<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
	<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
	<p>Find me in app/views/articles/edit.html.erb</p>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
	<p>Find me in app/views/articles/index.html.erb</p>

<div class="container">
  <h1>My articles</h1>
  <ul>
    <% @articles.each do |article| %>

          <div>
            <span><%= link_to article.title, article_path(article) %></span>

    <% end %>
  </ul>
  <div class="border-top">
    <div class="back-link">
      <i class="fas fa-plus"></i>
      <span><%= link_to "Add a new article", new_article_path %>
      </span>
    </div>
	  </div>
	</div>
</div>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
	<p>Find me in app/views/articles/new.html.erb</p>
<%= render 'form' %>
<%= link_to 'back', articles_path %>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
	<p>Find me in app/views/articles/show.html.erb</p>
  <%= @article.title %>
  <br>
  <%= @article.content %>
  <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
  <p>delete</p>
  <% end %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
	<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>